import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Confetti from "@/components/Confetti";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Confetti />
        <div>
          <h1 className={styles.heading}>
            Congrats @Bitbns for the upcoming Anniversary 🎉
          </h1>

          <p className={styles.subheading}>
            visit us 👉🏻{" "}
            <a className={styles.link} href="https://www.bitbns.com/">
              link
            </a>
          </p>
        </div>
      </main>
    </>
  );
}
